type Usuario {
    id: ID,
    nome: String,
    idade: Int,
    ativo: Boolean,
    perfil: Perfil
}

type Query {
    usuarios: [Usuario],
    usuario(id: ID): Usuario,
}

type Mutation {
    criarUsuario(nome: String, idade: Int, ativo: Boolean): Usuario!
}